name: notus
description: Platform-agnostic rich text document model based on Delta format and used in Zefyr editor.
version: 0.1.5
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
homepage: https://github.com/memspace/zefyr

environment:
  sdk: '>=2.8.4 <3.0.0'

dependencies:
  collection: ^1.14.13
  meta: ^1.2.3
  quill_delta: ^2.0.0
  quiver_hashcode: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
  test_coverage: ^0.4.3
